local require = require
require("Utils.DataTablaName")
require("Utils.MessageTags")
require("Utils.LuaCommon")
require("Utils.LuaTableMgr")
require("Global")
require("Framework.FrameworkInitRequire")
require("Rouge.Gameplay.C2SCommunication.Logic_HttpCommunication")
require("Modules.SystemTravel.SystemStateDef")
require("GameConfig.SystemOpen.SystemOpenID")
require("Rouge.UI.UIBase.UIConfig")
require("Rouge.UI.UIBase.UILayerGroup")
require("Rouge.UI.UIBase.RGUIMgr")
_G.ModuleManager:Init()
