
--系统ID定义
--https://alidocs.dingtalk.com/i/nodes/Qnp9zOoBVBZ6K9bAFpedqK0RV1DK0g6l?utm_scene=team_space&utm_source=dingdoc_doc&utm_medium=dingdoc_doc_splitview
SystemOpenID = {
    MATCH = "match",--匹配功能
    START_GAME = "start_game",--开始游戏功能
    TEAM_INVITE = "team_invite",--邀请组队功能
    CHAT = "chat",--聊天界面
    CHOU_KA = "chou_ka",--抽卡界面
    SEVEN_DAYS_AWARDS = "seven_day_awards",--七日奖励界面
    SEVEN_DAYS_ACTIVITE = "seven_day_activity",--七日活动界面
    WEAPON = "weapon",--武器界面
    MATRIX = "matrix",--战斗矩阵界面
    HERO_MASTERY = "hero_mastery",--英雄熟练度界面
    HERO_SKIN = "hero_skin",--英雄外观界面
    TALENT = "talent",--能力模块界面
    DROPS_UP_LOBBY = "drops_up_lobby",--局内掉落上传大厅服功能
    FRIENDS = "friends",--好友界面
    TUTORIAL = "tutorial",--教程界面
    MAIL = "mail",--邮件界面
    ANNOUNCEMENT = "announcement",--公告界面
    CAREER = "career",--生涯界面
    INFORMATION_CHANGE = "information_change",--个人信息修改
    ACHIEVEMENT = "achievement",--成就界面
    HISTORY = "history",--历史战绩界面
    TASK = "task",--任务进度
    MALL = "mall", --商城
    PURCHASE = "purchase",--充值子界面
    RECOMMEND = "recommend",--推荐子界面
    BUNDLE = "bundle",--捆绑包子界面
    EXTERIOR = "exterior",--外观子界面
    PROPS = "props",--常驻商品子界面
    EXTERIOR_1 = "exterior_1",--晶体商城子界面
    MONTHCARD = "monthcard",--权益子界面
    RANK = "rank",--排行榜界面
    TU_JIAN = "tu_jian",--图鉴主界面
    QIAN_NENG_MI_YAO = "qian_neng_mi_yao",--潜能秘钥界面
    QUAN_XIAN = "quan_xian",--权限界面
    STORY_PIECES = "story_pieces",--剧情碎片
    DELATE = "delate",--举报界面
    SETTINGS = "settings",--设置界面
    PASS = "pass",--通行证界面
    RECRUIT = "recruit",--招募界面
    GM = "gm",--联系客服界面
    EXCHANGE = "exchange",--兑换界面
    SEASON = "season",--赛季界面
    SEASON_MODE_POP = "season_mode_pop",--赛季KV弹窗
    GAME_MODE_1001 = "game_mode_1001",--常规模式
    GAME_MODE_1002 = "game_mode_1002",--无尽模式
    GAME_MODE_1003 = "game_mode_1003",--修正行动
    GAME_MODE_2001 = "game_mode_2001",--初入环都
    GAME_MODE_3001 = "game_mode_3001",--失序链区
    GAME_MODE_3002 = "game_mode_3002",--病毒狂潮
    GAME_MODE_3000 = "game_mode_3000",--基础模式
    DAILYREWARDS = "dailyRewards",--每日奖励
    CLIMB_TOWER_RANK = "climb_tower_rank",--爬塔排行榜
    SERVER_SELECT = "server_select",--大厅服务器选择，暂时不做
}